FROM  ubuntu:focal

LABEL maintainer="Andrei.Shvarts@glasgow.ac.uk"

# general environment for docker
ENV DEBIAN_FRONTEND=noninteractive \
    SPACK_ROOT=/usr/local \
    FORCE_UNSAFE_CONFIGURE=1

# timezone env with default
ENV TZ Europe/London

# Config apt-get
RUN echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/99local

ENV DEBIAN_FRONTEND=noninteractive

# Install packages
RUN apt-get update && \
apt-get install -y \
file \
zlib1g-dev \
openssh-server \
wget \
valgrind \
curl \
git \
g++ \
gfortran \
gdb \
m4 \
automake \
build-essential \
libtool \
libblas-dev \
liblapack-dev \
libpython3.8-dev \
libsigsegv2 \
libjpeg-dev \
graphviz \
doxygen \
cmake \
pkg-config \
gnuplot \
ca-certificates \
python \
python-dev \
python3-distutils \
libx11-dev \
xauth \
xterm \
unzip \
mesa-common-dev \
libglu1-mesa-dev \
libxmu-dev \
libxi-dev \
libssl-dev \
gawk \
libopenmpi-dev \
&& rm -rf /var/lib/apt/lists/*

ENV INSTALL_DIR=/container

#ENV TARGET=x86_64 
ENV TARGET=aarch64 

# image run hook: the -l will make sure /etc/profile environments are loaded
CMD /bin/bash -l

# SSH .ssh dir
RUN mkdir root/.ssh

# Allow to trace child procsses needed for debuging
RUN sed  -i 's/kernel.yama.ptrace_scope = 1/kernel.yama.ptrace_scope = 0/' /etc/sysctl.d/10-ptrace.conf

# Create the PrivSep empty dir if necessary
RUN if [ ! -d /var/run/sshd ]; then \
   mkdir /var/run/sshd; \
   chmod 0755 /var/run/sshd; \
   fi

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
